[package]
name = "deltachat-provider-overview"
version = "0.1.0"
authors = ["simon <deltachat-provider-overview@simonlaux.de>"]
edition = "2018"
build = "build.rs"

[dependencies]


[build-dependencies]
glob = "0.3.0"
regex = "1"
lazy_static = "1.3.0"
yaml-rust = "0.4.3"