[package]
name = "deltachat-provider-overview"
version = "0.1.0"
authors = ["simon <deltachat-provider-overview@simonlaux.de>"]
edition = "2018"
build = "build.rs"

[dependencies]


[build-dependencies]