name: Deploy Preview

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Can we upload the preview?  # Get Pullrequest ID
      id: prepare
      run: |
#       export PULLREQUEST_ID=$(echo "${{ github.ref }}" | cut -d "/" -f3)
#       echo ::set-output name=prid::$PULLREQUEST_ID
        if [ $(expr length "${{ secrets.USERNAME }}") -gt "1" ]; then echo ::set-output name=uploadtoserver::true ;fi
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - name: Upload
      uses: appleboy/scp-action@master
      env:
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
        HOST: testrun.org
        PORT: 22
        SOURCE: _site
        TARGET: providerOverview/${{ github.sha }}/
    - name: "Post links to details"
      if: steps.prepare.outputs.uploadtoserver
      run: |
        # URLs for API connection and uploads
        export GITHUB_API_URL="https://api.github.com/repos/deltachat/provider-db/statuses/${{ github.event.after }}"
        export PREVIEW_LINK="https://testrun.org/provider/${{ github.sha }}/_site/"
        # Post AppImage download link to check details
        export STATUS_DATA="{\"state\": \"success\", \
                             \"description\": \"Preview the page here:\", \
                             \"context\": \"Page Preview\", \
                             \"target_url\": \"${PREVIEW_LINK}\"}"
        curl -X POST --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" --url "$GITHUB_API_URL" --header "content-type: application/json" --data "$STATUS_DATA"
#   - name: "post Link"
#     uses: rytswd/respost@v0.1.0
#     with:
#       title: "Preview changes"
#       body: "Preview at: https://testrun.org/provider/${{ github.sha }}/_site/"
#     env:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
